In [248]:
import pandas as pd
import numpy as np
import random

In [263]:
df_atracciones=pd.read_csv('/Users/h.adrianzabaletahernandez/Desktop/ArchivosCSVProyecto-Pontia2024/atracciones.csv')

In [296]:
df_atracciones[df_atracciones['id_visitante']==3]

,id_visitante,t_id,atraccion,comienzo_atraccion,tiempo_de_espera
0,3,Training_10118481.jpg,Montaña Rusa de la Luna,291.0,5
1,3,Training_15361067.jpg,Mansión Embrujada,180.0,11
2,3,Training_16232328.jpg,Simulador Espacial 3D,384.0,19
3,3,Training_27705571.jpg,Fiesta de los Dulces,625.0,9
4,3,Training_63766171.jpg,Gran Caída Libre,613.0,17
5,3,Training_66555113.jpg,Cine 4D Emocionante,533.0,18
6,3,Training_81499267.jpg,Tobogán del Arco Iris,297.0,19
7,3,Training_94007493.jpg,Vuelo Mágico,82.0,7
8,3,Training_12950225.jpg,Araña Saltarina,316.0,9
9,3,Training_42955258.jpg,Tobogán del Arco Iris,552.0,10
10,3,Training_50338135.jpg,Cine 4D Emocionante,417.0,9
11,3,Training_65820611.jpg,Mundo de las Maravillas,698.0,9
12,3,Training_8397060.jpg,Mansión Embrujada,716.0,11
13,3,Training_90069123.jpg,Simulador Espacial 3D,414.0,9
14,3,Training_28136915.jpg,Mansión Embrujada,2.0,14
15,3,Training_52516519.jpg,Mansión Embrujada,583.0,20
16,3,Training_61794811.jpg,Fiesta de los Dulces,88.0,19
17,3,Training_66142455.jpg,Mundo de las Maravillas,237.0,16
18,3,Training_72798447.jpg,Cohetes Galácticos,183.0,5
19,3,Training_78245467.jpg,Cohetes Galácticos,156.0,16
20,3,Training_83065372.jpg,Safari Salvaje,241.0,19
21,3,Training_87355987.jpg,Barco Pirata Misterioso,539.0,14
22,3,Training_88196061.jpg,Montaña del Misterio,524.0,12
23,3,Training_29363112.jpg,Mundo de las Maravillas,504.0,16
24,3,Training_36501565.jpg,Selva Encantada,352.0,13
25,3,Training_53284079.jpg,Cohetes Galácticos,156.0,15
26,3,Training_53305606.jpg,Jardín de las Hadas,321.0,12
27,3,Training_20716064.jpg,Cine 4D Emocionante,658.0,15
28,3,Training_61325993.jpg,Espejos de la Risueña,308.0,8
29,3,Training_61564918.jpg,Mansión Embrujada,37.0,14
30,3,Training_75082078.jpg,Laberinto de Sueños,510.0,13
31,3,PublicTest_43074366.jpg,Dragón Volador,121.0,14
32,3,PublicTest_28123281.jpg,Selva Encantada,524.0,22
33,3,PublicTest_75651978.jpg,Dragón Volador,394.0,14
34,3,PrivateTest_92593957.jpg,Carros Chocones Divertidos,360.0,15
35,3,PrivateTest_98556225.jpg,Carros Chocones Divertidos,645.0,13

In [276]:
df_atracciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35887 entries, 0 to 35886
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_visitante        35887 non-null  int64
 1   t_id                35887 non-null  object
 2   atraccion           34749 non-null  object
 3   comienzo_atraccion  35791 non-null  float64
 4   tiempo_de_espera    35887 non-null  int64
dtypes: float64(1), int64(2), object(2)
memory usage: 1.4+ MB

In [275]:
#Podemos eliminarlos?
df_atracciones[(df_atracciones['comienzo_atraccion']<0) | (df_atracciones['atraccion'].isnull()) | (df_atracciones['comienzo_atraccion'].isnull())]

,id_visitante,t_id,atraccion,comienzo_atraccion,tiempo_de_espera
56,4,Training_85932660.jpg,NaN,596.0,4
59,4,Training_1204614.jpg,NaN,426.0,21
60,4,Training_15524948.jpg,NaN,100.0,8
61,4,Training_57944429.jpg,NaN,477.0,13
82,5,Training_81192903.jpg,Barco Pirata Misterioso,NaN,12
...,...,...,...,...,...
35801,1735,PublicTest_62426646.jpg,NaN,108.0,13
35815,1741,PrivateTest_23030368.jpg,NaN,404.0,11
35828,1749,PrivateTest_93071746.jpg,NaN,80.0,18
35860,1768,PublicTest_93328347.jpg,NaN,562.0,13
35886,1787,PublicTest_94828377.jpg,NaN,417.0,13

In [299]:
df_atracciones[(df_atracciones['comienzo_atraccion']>15) & (df_atracciones['comienzo_atraccion']<20)]

,id_visitante,t_id,atraccion,comienzo_atraccion,tiempo_de_espera
63,4,Training_72115626.jpg,Simulador Espacial 3D,18.0,13
124,6,Training_12302906.jpg,Caravana de Aventuras,18.0,11
226,9,Training_14669195.jpg,Cúpula Estelar,19.0,17
472,16,Training_41052937.jpg,Cine 4D Emocionante,19.0,7
543,18,Training_45060957.jpg,Circus Fantástico,18.0,19
...,...,...,...,...,...
35116,1578,PrivateTest_8115978.jpg,Tren del Terror,16.0,11
35159,1586,PublicTest_26383670.jpg,Vuelta al Mundo en 80 Días,19.0,8
35450,1636,PublicTest_20014869.jpg,Espejos de la Risueña,19.0,7
35559,1659,PrivateTest_61277100.jpg,Montaña del Misterio,17.0,14
35835,1753,PublicTest_21175427.jpg,Aventuras Acuáticas,16.0,7

In [258]:
df_con_id=df_atracciones.groupby(['atraccion']).agg({'atraccion':'size'})

In [251]:
df_atracciones.drop(columns=['id_visitante'],inplace=True)
df_atracciones.columns.values.tolist()

['t_id', 'atraccion', 'comienzo_atraccion', 'tiempo_de_espera']

In [178]:
df=df_atracciones.groupby(['t_id']).apply(lambda x: x[[ 'atraccion', 'comienzo_atraccion', 'tiempo_de_espera']].to_dict('records')).reset_index().rename(columns={0:'prueba'})
df

/var/folders/z7/nbzy91552pxg2z1dxj_q975w0000gn/T/ipykernel_5401/3962445746.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df=df_atracciones.groupby(['t_id']).apply(lambda x: x[[ 'atraccion', 'comienzo_atraccion', 'tiempo_de_espera']].to_dict('records')).reset_index().rename(columns={0:'prueba'})

,t_id,prueba
0,PrivateTest_10072988.jpg,"[{'atraccion': 'Aventuras Acuáticas', 'comienz..."
1,PrivateTest_10077120.jpg,"[{'atraccion': 'Barco Pirata Misterioso', 'com..."
2,PrivateTest_10086748.jpg,"[{'atraccion': 'Cohetes Galácticos', 'comienzo..."
3,PrivateTest_10089743.jpg,"[{'atraccion': 'Vuelta al Mundo en 80 Días', '..."
4,PrivateTest_10131363.jpg,"[{'atraccion': 'Rápido del Trueno', 'comienzo_..."
...,...,...
35880,Training_99984859.jpg,"[{'atraccion': 'Cascada Encantada', 'comienzo_..."
35881,Training_99987906.jpg,"[{'atraccion': 'Vuelta al Mundo en 80 Días', '..."
35882,Training_99988263.jpg,"[{'atraccion': 'Mundo de las Maravillas', 'com..."
35883,Training_99996831.jpg,"[{'atraccion': 'Laberinto de Sueños', 'comienz..."
35884,Training_99999696.jpg,"[{'atraccion': 'Cine 4D Emocionante', 'comienz..."

In [179]:
df.isnull().sum()

t_id      0
prueba    0
dtype: int64

In [280]:
df_atracciones.head(5)

,id_visitante,t_id,atraccion,comienzo_atraccion,tiempo_de_espera
0,3,Training_10118481.jpg,Montaña Rusa de la Luna,291.0,5
1,3,Training_15361067.jpg,Mansión Embrujada,180.0,11
2,3,Training_16232328.jpg,Simulador Espacial 3D,384.0,19
3,3,Training_27705571.jpg,Fiesta de los Dulces,625.0,9
4,3,Training_63766171.jpg,Gran Caída Libre,613.0,17

In [181]:
#Comprobamos que el tiempo de recogida coincide con la cantidad de horas de los datos. EL total de horas son 720.
df_atracciones['comienzo_atraccion'].max()

719.0

In [182]:
df_atracciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35887 entries, 0 to 35886
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   t_id                35887 non-null  object
 1   atraccion           34749 non-null  object
 2   comienzo_atraccion  35791 non-null  float64
 3   tiempo_de_espera    35887 non-null  int64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.1+ MB

In [183]:
df_atracciones.isnull().sum()

t_id                     0
atraccion             1138
comienzo_atraccion      96
tiempo_de_espera         0
dtype: int64

In [184]:
df_atracciones.isna().sum()

t_id                     0
atraccion             1138
comienzo_atraccion      96
tiempo_de_espera         0
dtype: int64

In [185]:
t_id=df_atracciones['t_id'].unique()
lista_atracciones=list(t_id)
print(len(lista_atracciones))

35885

In [186]:
df_atracciones.head(50)

,t_id,atraccion,comienzo_atraccion,tiempo_de_espera
0,Training_10118481.jpg,Montaña Rusa de la Luna,291.0,5
1,Training_15361067.jpg,Mansión Embrujada,180.0,11
2,Training_16232328.jpg,Simulador Espacial 3D,384.0,19
3,Training_27705571.jpg,Fiesta de los Dulces,625.0,9
4,Training_63766171.jpg,Gran Caída Libre,613.0,17
5,Training_66555113.jpg,Cine 4D Emocionante,533.0,18
6,Training_81499267.jpg,Tobogán del Arco Iris,297.0,19
7,Training_94007493.jpg,Vuelo Mágico,82.0,7
8,Training_12950225.jpg,Araña Saltarina,316.0,9
9,Training_42955258.jpg,Tobogán del Arco Iris,552.0,10
10,Training_50338135.jpg,Cine 4D Emocionante,417.0,9
11,Training_65820611.jpg,Mundo de las Maravillas,698.0,9
12,Training_8397060.jpg,Mansión Embrujada,716.0,11
13,Training_90069123.jpg,Simulador Espacial 3D,414.0,9
14,Training_28136915.jpg,Mansión Embrujada,2.0,14
15,Training_52516519.jpg,Mansión Embrujada,583.0,20
16,Training_61794811.jpg,Fiesta de los Dulces,88.0,19
17,Training_66142455.jpg,Mundo de las Maravillas,237.0,16
18,Training_72798447.jpg,Cohetes Galácticos,183.0,5
19,Training_78245467.jpg,Cohetes Galácticos,156.0,16
20,Training_83065372.jpg,Safari Salvaje,241.0,19
21,Training_87355987.jpg,Barco Pirata Misterioso,539.0,14
22,Training_88196061.jpg,Montaña del Misterio,524.0,12
23,Training_29363112.jpg,Mundo de las Maravillas,504.0,16
24,Training_36501565.jpg,Selva Encantada,352.0,13
25,Training_53284079.jpg,Cohetes Galácticos,156.0,15
26,Training_53305606.jpg,Jardín de las Hadas,321.0,12
27,Training_20716064.jpg,Cine 4D Emocionante,658.0,15
28,Training_61325993.jpg,Espejos de la Risueña,308.0,8
29,Training_61564918.jpg,Mansión Embrujada,37.0,14
30,Training_75082078.jpg,Laberinto de Sueños,510.0,13
31,PublicTest_43074366.jpg,Dragón Volador,121.0,14
32,PublicTest_28123281.jpg,Selva Encantada,524.0,22
33,PublicTest_75651978.jpg,Dragón Volador,394.0,14
34,PrivateTest_92593957.jpg,Carros Chocones Divertidos,360.0,15
35,PrivateTest_98556225.jpg,Carros Chocones Divertidos,645.0,13
36,Training_10120469.jpg,Carrusel Encantado,425.0,11
37,Training_15848209.jpg,Viaje al Centro de la Tierra,363.0,16
38,Training_19226789.jpg,Montaña Rusa de la Luna,15.0,12
39,Training_2729866.jpg,Mansión Embrujada,277.0,12
40,Training_2978709.jpg,Caravana de Aventuras,338.0,16
41,Training_50449072.jpg,Cascada Encantada,655.0,8
42,Training_59169722.jpg,Carrusel Encantado,389.0,20
43,Training_72552568.jpg,Gran Caída Libre,197.0,10
44,Training_8911067.jpg,Carrera de Autos Locos,608.0,9
45,Training_19237812.jpg,Rápido del Trueno,469.0,14
46,Training_37488451.jpg,Montaña Rusa de la Luna,582.0,16
47,Training_4879752.jpg,Laberinto de Sueños,214.0,12
48,Training_94085355.jpg,Montaña Rusa de la Luna,196.0,5
49,Training_99751984.jpg,Vuelta al Mundo en 80 Días,87.0,7

In [187]:
df_atracciones[df_atracciones['atraccion'].isnull()]

,t_id,atraccion,comienzo_atraccion,tiempo_de_espera
56,Training_85932660.jpg,NaN,596.0,4
59,Training_1204614.jpg,NaN,426.0,21
60,Training_15524948.jpg,NaN,100.0,8
61,Training_57944429.jpg,NaN,477.0,13
85,Training_91019189.jpg,NaN,598.0,17
...,...,...,...,...
35801,PublicTest_62426646.jpg,NaN,108.0,13
35815,PrivateTest_23030368.jpg,NaN,404.0,11
35828,PrivateTest_93071746.jpg,NaN,80.0,18
35860,PublicTest_93328347.jpg,NaN,562.0,13
35886,PublicTest_94828377.jpg,NaN,417.0,13

In [188]:
filas_con_nulos = df_atracciones[df_atracciones['atraccion'].isnull() & df_atracciones['comienzo_atraccion'].isnull()]
filas_con_nulos

                          t_id atraccion  comienzo_atraccion  tiempo_de_espera
4641     Training_98791138.jpg       NaN                 NaN                 5
12219   PublicTest_2067774.jpg       NaN                 NaN                 9
13958  PrivateTest_3362951.jpg       NaN                 NaN                14
31448  PublicTest_93901885.jpg       NaN                 NaN                 4

In [189]:
df_atracciones[df_atracciones['comienzo_atraccion'].isnull()]

,t_id,atraccion,comienzo_atraccion,tiempo_de_espera
82,Training_81192903.jpg,Barco Pirata Misterioso,NaN,12
386,Training_10333072.jpg,Carrusel Encantado,NaN,17
1280,Training_13081724.jpg,Cohetes Galácticos,NaN,16
2445,Training_67457164.jpg,Tren del Terror,NaN,10
2630,Training_60936737.jpg,Cohetes Galácticos,NaN,10
...,...,...,...,...
34558,Training_98381187.jpg,Carrusel Encantado,NaN,13
34915,PrivateTest_56190110.jpg,Circus Fantástico,NaN,5
35076,Training_73211625.jpg,Circus Fantástico,NaN,8
35258,PrivateTest_39819887.jpg,Torbellino Espacial,NaN,15
35548,PrivateTest_23899463.jpg,Selva Encantada,NaN,23

In [190]:
df_atracciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35887 entries, 0 to 35886
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   t_id                35887 non-null  object
 1   atraccion           34749 non-null  object
 2   comienzo_atraccion  35791 non-null  float64
 3   tiempo_de_espera    35887 non-null  int64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.1+ MB

In [253]:
#Vamos a sustituir los valores nulos de la columnna comienzo de atracción. Y los valores que superen el tiempo de toma de los datos.
#Para ello crearemos una lista aleatoria con el total del tiempo - 1 de los datos
#utilizamos un bucle for con una selección aleatoria para sustituir los valores nulos. 
tiempo = [random.randint(1, 704) for i in range(96)]
for i in range(len(df_atracciones)):
    if pd.isnull(df_atracciones.loc[i,'comienzo_atraccion']):
         df_atracciones.loc[i, 'comienzo_atraccion'] = random.choice(tiempo)
    if df_atracciones.loc[i,'comienzo_atraccion']>705:
         df_atracciones.loc[i, 'comienzo_atraccion'] = random.choice(tiempo)

In [192]:
df_atracciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35887 entries, 0 to 35886
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   t_id                35887 non-null  object
 1   atraccion           34749 non-null  object
 2   comienzo_atraccion  35887 non-null  float64
 3   tiempo_de_espera    35887 non-null  int64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.1+ MB

In [254]:
#Estamos creando una lista con las atracciones.
atr=df_atracciones['atraccion'].unique()
lista_atracciones=list(atr)
lista_atracciones = [x for x in lista_atracciones if pd.notna(x)]
#lista_atracciones.pop()#una solución un poco chapucera. No entiendo porque no me funciona lo de arriba.

In [208]:
lista_atracciones

['Montaña Rusa de la Luna',
 'Mansión Embrujada',
 'Simulador Espacial 3D',
 'Fiesta de los Dulces',
 'Gran Caída Libre',
 'Cine 4D Emocionante',
 'Tobogán del Arco Iris',
 'Vuelo Mágico',
 'Araña Saltarina',
 'Mundo de las Maravillas',
 'Cohetes Galácticos',
 'Safari Salvaje',
 'Barco Pirata Misterioso',
 'Montaña del Misterio',
 'Selva Encantada',
 'Jardín de las Hadas',
 'Espejos de la Risueña',
 'Laberinto de Sueños',
 'Dragón Volador',
 'Carros Chocones Divertidos',
 'Carrusel Encantado',
 'Viaje al Centro de la Tierra',
 'Caravana de Aventuras',
 'Cascada Encantada',
 'Carrera de Autos Locos',
 'Rápido del Trueno',
 'Vuelta al Mundo en 80 Días',
 'Cúpula Estelar',
 'Circuito Veloz',
 nan,
 'Aventuras Acuáticas',
 'Tirolina Extrema',
 'Circus Fantástico',
 'Torbellino Espacial',
 'Rueda de la Fortuna',
 'Tren del Terror']

In [255]:
#Vamos a susutituir los valores nulos de la columna atracción mediante una selección aleatoria,
#para ello utilizaremos un bucle for. Utilizaremos la lista creada anteriormente.
for i in range(len(df_atracciones)):
    if pd.isnull(df_atracciones.loc[i, 'atraccion']):
        df_atracciones.loc[i, 'atraccion'] = random.choice(lista_atracciones)

In [256]:
#De esta manera quitamos el valor str "nan" que se nos quedó de la interación anterior, al no haber eliminado "nan" de la lista.
df_atracciones['atraccion'] = df_atracciones['atraccion'].replace("nan", random.choice(lista_atracciones))

In [259]:
df_sin_nulos=df_atracciones.groupby(['atraccion']).agg({'atraccion':'size'})

In [278]:
df_sin_nulos

                              atraccion
atraccion
Araña Saltarina                    1026
Aventuras Acuáticas                1048
Barco Pirata Misterioso            1025
Caravana de Aventuras              1009
Carrera de Autos Locos             1024
Carros Chocones Divertidos         1039
Carrusel Encantado                  989
Cascada Encantada                  1003
Cine 4D Emocionante                1015
Circuito Veloz                     1021
Circus Fantástico                  1055
Cohetes Galácticos                 1020
Cúpula Estelar                     1018
Dragón Volador                     1016
Espejos de la Risueña              1001
Fiesta de los Dulces               1035
Gran Caída Libre                   1007
Jardín de las Hadas                1027
Laberinto de Sueños                1029
Mansión Embrujada                  1056
Montaña Rusa de la Luna            1044
Montaña del Misterio               1008
Mundo de las Maravillas            1044
Rueda de la Fortuna                1051
Rápido del Trueno                  1048
Safari Salvaje                     1009
Selva Encantada                     999
Simulador Espacial 3D              1006
Tirolina Extrema                   1040
Tobogán del Arco Iris              1025
Torbellino Espacial                1016
Tren del Terror                    1019
Viaje al Centro de la Tierra       1001
Vuelo Mágico                       1029
Vuelta al Mundo en 80 Días         1085

In [199]:
df_atracciones['comienzo_atraccion']=df_atracciones['comienzo_atraccion'].abs()

In [223]:
df_atracciones[df_atracciones['atraccion'].isnull()]

Empty DataFrame
Columns: [t_id, atraccion, comienzo_atraccion, tiempo_de_espera]
Index: []

In [224]:
df_atracciones.to_csv('atracciones_sql.csv', index=False)

In [234]:
df_atracciones[df_atracciones['t_id']=='PrivateTest_88305.jpg']

,t_id,atraccion,comienzo_atraccion,tiempo_de_espera
33882,PrivateTest_88305.jpg,Circuito Veloz,1.0,13

In [229]:
df_atracciones.head(20)

,t_id,atraccion,comienzo_atraccion,tiempo_de_espera
0,Training_10118481.jpg,Montaña Rusa de la Luna,291.0,5
1,Training_15361067.jpg,Mansión Embrujada,180.0,11
2,Training_16232328.jpg,Simulador Espacial 3D,384.0,19
3,Training_27705571.jpg,Fiesta de los Dulces,625.0,9
4,Training_63766171.jpg,Gran Caída Libre,613.0,17
5,Training_66555113.jpg,Cine 4D Emocionante,533.0,18
6,Training_81499267.jpg,Tobogán del Arco Iris,297.0,19
7,Training_94007493.jpg,Vuelo Mágico,82.0,7
8,Training_12950225.jpg,Araña Saltarina,316.0,9
9,Training_42955258.jpg,Tobogán del Arco Iris,552.0,10
10,Training_50338135.jpg,Cine 4D Emocionante,417.0,9
11,Training_65820611.jpg,Mundo de las Maravillas,698.0,9
12,Training_8397060.jpg,Mansión Embrujada,526.0,11
13,Training_90069123.jpg,Simulador Espacial 3D,414.0,9
14,Training_28136915.jpg,Mansión Embrujada,2.0,14
15,Training_52516519.jpg,Mansión Embrujada,583.0,20
16,Training_61794811.jpg,Fiesta de los Dulces,88.0,19
17,Training_66142455.jpg,Mundo de las Maravillas,237.0,16
18,Training_72798447.jpg,Cohetes Galácticos,183.0,5
19,Training_78245467.jpg,Cohetes Galácticos,156.0,16

In [281]:
df_atracciones_2=pd.read_csv("/Users/h.adrianzabaletahernandez/Desktop/ArchivosCSVProyecto-Pontia2024/atracciones_sql.csv")

In [302]:
# Agrupar fotos por combinación de 'atraccion', 'comienzo_atraccion' y 'tiempo_de_espera'
grupo_fotos = df_atracciones_2.groupby(['atraccion', 'comienzo_atraccion', 'tiempo_de_espera'])['t_id'].apply(list).reset_index()
#['t_id'].apply(list): Convierte los identificadores de foto en listas para cada grupo.
# Mostrar el resultado
grupo_fotos.sample(50)

,atraccion,comienzo_atraccion,tiempo_de_espera,t_id
776,Araña Saltarina,537.0,13,"[Training_16288109.jpg, Training_39736221.jpg]"
17186,Jardín de las Hadas,452.0,7,[Training_94448240.jpg]
29566,Torbellino Espacial,207.0,13,[Training_83474295.jpg]
5709,Carros Chocones Divertidos,581.0,8,[Training_53256024.jpg]
32616,Vuelo Mágico,363.0,17,[Training_35338894.jpg]
24199,Rápido del Trueno,516.0,10,[Training_44695354.jpg]
21721,Mundo de las Maravillas,209.0,9,[Training_47232613.jpg]
22886,Rueda de la Fortuna,300.0,12,[Training_47380128.jpg]
6425,Carrusel Encantado,404.0,13,[Training_62401758.jpg]
32164,Vuelo Mágico,24.0,17,[Training_94884420.jpg]
24666,Safari Salvaje,135.0,10,[Training_33283812.jpg]
9337,Circuito Veloz,419.0,12,[Training_51810677.jpg]
4583,Carrera de Autos Locos,512.0,12,[PrivateTest_24272642.jpg]
532,Araña Saltarina,374.0,4,[Training_8970577.jpg]
11629,Cohetes Galácticos,647.0,20,[Training_37585633.jpg]
25115,Safari Salvaje,462.0,14,[PublicTest_76152057.jpg]
1417,Aventuras Acuáticas,290.0,16,[Training_93069871.jpg]
8806,Circuito Veloz,27.0,12,[Training_13177515.jpg]
410,Araña Saltarina,289.0,18,[Training_11888118.jpg]
22339,Mundo de las Maravillas,619.0,12,[PrivateTest_97342741.jpg]
27543,Tirolina Extrema,125.0,21,[Training_57385265.jpg]
26602,Simulador Espacial 3D,163.0,12,[Training_63238670.jpg]
10417,Circus Fantástico,476.0,16,[Training_28766758.jpg]
32928,Vuelo Mágico,568.0,10,[Training_6321346.jpg]
10668,Circus Fantástico,649.0,14,[Training_45480019.jpg]
23240,Rueda de la Fortuna,545.0,16,[Training_80785973.jpg]
23570,Rápido del Trueno,71.0,11,[Training_1359028.jpg]
22303,Mundo de las Maravillas,597.0,15,[Training_81312912.jpg]
1155,Aventuras Acuáticas,108.0,7,[Training_99095418.jpg]
2397,Barco Pirata Misterioso,304.0,12,[Training_42185251.jpg]
13121,Dragón Volador,328.0,18,[Training_91439170.jpg]
87,Araña Saltarina,57.0,19,[Training_54583631.jpg]
27370,Tirolina Extrema,19.0,8,"[Training_96207763.jpg, Training_18725515.jpg]"
15128,Fiesta de los Dulces,365.0,8,[PublicTest_40423206.jpg]
4081,Carrera de Autos Locos,123.0,12,[Training_40824163.jpg]
27896,Tirolina Extrema,393.0,15,[Training_3490947.jpg]
14163,Espejos de la Risueña,387.0,18,[PublicTest_32156077.jpg]
17992,Laberinto de Sueños,322.0,13,[PrivateTest_2921450.jpg]
11017,Cohetes Galácticos,208.0,9,[PrivateTest_75630029.jpg]
6178,Carrusel Encantado,224.0,13,[Training_78580098.jpg]
31917,Viaje al Centro de la Tierra,551.0,7,[Training_3561462.jpg]
12496,Cúpula Estelar,562.0,21,[Training_5744349.jpg]
30410,Tren del Terror,119.0,16,[PrivateTest_78614220.jpg]
31632,Viaje al Centro de la Tierra,344.0,12,"[Training_96702800.jpg, PublicTest_34052482.jpg]"
21371,Montaña del Misterio,627.0,13,[PrivateTest_77173489.jpg]
24689,Safari Salvaje,147.0,17,[Training_63024018.jpg]
32443,Vuelo Mágico,233.0,9,[Training_26800697.jpg]
17829,Laberinto de Sueños,201.0,19,[Training_29807870.jpg]
17187,Jardín de las Hadas,453.0,4,[Training_23800278.jpg]
8517,Cine 4D Emocionante,528.0,12,[PrivateTest_26560060.jpg]